//! Original numerical fixtures. None are measured engine/aircraft data.
use super::*;
use crate::turboprop as law1;
use flightsim_core::{Meters, MetersPerSecond, Newtons};
use law1::{
    GovernorDefinition, PowerCellDefinition, PropellerConvention, PropellerDefinition,
    TurbineDefinition, TurbopropEnvelopeDefinition,
};
use serde::{Deserialize, Serialize};
use serde_json::{Value, value::RawValue};
use std::collections::BTreeMap;

#[derive(Deserialize, Serialize)]
struct CedarComponents {
    airframe: AirframeDefinition,
    aero: MachAeroDefinition,
    turbine: TurbineDefinition,
    propeller: PropellerDefinition,
    governor: GovernorDefinition,
    envelope: TurbopropEnvelopeDefinition,
}
// Fixture-only adapter, not a production profile reader. Raw tokens first go
// through Rust's correctly rounded parser, then Value stores those exact bits.
// Ordinary serde_json f64 token conversion is never used for physical values.
fn exact_fixture_value(raw: &RawValue) -> Value {
    let token = raw.get();
    match token.as_bytes()[0] {
        b'{' => {
            let fields: BTreeMap<String, &RawValue> = serde_json::from_str(token).unwrap();
            Value::Object(
                fields
                    .into_iter()
                    .map(|(key, value)| (key, exact_fixture_value(value)))
                    .collect(),
            )
        }
        b'[' => {
            let values: Vec<&RawValue> = serde_json::from_str(token).unwrap();
            Value::Array(values.into_iter().map(exact_fixture_value).collect())
        }
        b'"' | b'n' | b't' | b'f' => serde_json::from_str(token).unwrap(),
        _ if token.contains(['.', 'e', 'E']) || token == "-0" => {
            Value::Number(serde_json::Number::from_f64(token.parse::<f64>().unwrap()).unwrap())
        }
        // Preserve integer schema/sense tags; all fixture integers fit binary64.
        _ => serde_json::from_str(token).unwrap(),
    }
}
fn cedar_forward() -> law1::TurbopropAircraftConfig {
    let raw: &RawValue = serde_json::from_str(include_str!(
        "../../../tests/fixtures/cedar-law1-components.json"
    ))
    .unwrap();
    let d: CedarComponents = serde_json::from_value(exact_fixture_value(raw)).unwrap();
    law1::TurbopropAircraftConfig::new(
        d.airframe.to_config().unwrap(),
        TurbinePowerTable::from_definition(d.turbine).unwrap(),
        law1::PropellerMap::from_definition(d.propeller).unwrap(),
        SampledGovernor::from_definition(d.governor).unwrap(),
        MachAeroSchedule::from_definition(d.aero).unwrap(),
        TurbopropEnvelope::from_definition(d.envelope).unwrap(),
    )
    .unwrap()
}

fn numeric_inventory(value: &Value, path: &str, output: &mut BTreeMap<String, String>) {
    match value {
        Value::Number(n) => {
            output.insert(
                path.to_owned(),
                format!("{:016x}", n.as_f64().unwrap().to_bits()),
            );
        }
        Value::Array(values) => {
            for (i, value) in values.iter().enumerate() {
                numeric_inventory(value, &format!("{path}/{i}"), output);
            }
        }
        Value::Object(fields) => {
            for (key, value) in fields {
                numeric_inventory(value, &format!("{path}/{key}"), output);
            }
        }
        _ => {}
    }
}

#[test]
fn cedar_component_bits_match_the_independent_original_profile_inventory() {
    let config = cedar_forward();
    // Inventory the constructed component getters, not another copy of the
    // test adapter's input. The witness was independently generated by Python
    // directly from the original production profile at the pinned commit.
    let recovered = CedarComponents {
        airframe: AirframeDefinition::from_config(config.airframe()),
        aero: config.aero().definition().clone(),
        turbine: config.turbine().definition().clone(),
        propeller: config.propeller().definition().clone(),
        governor: *config.governor().definition(),
        envelope: *config.envelope().definition(),
    };
    let mut actual = BTreeMap::new();
    numeric_inventory(&serde_json::to_value(recovered).unwrap(), "", &mut actual);
    let witness: Value = serde_json::from_str(include_str!(
        "../../../tests/fixtures/cedar-law1-component-bits.json"
    ))
    .unwrap();
    assert_eq!(
        serde_json::to_value(actual).unwrap(),
        witness["component_numeric_bits"]
    );
}
fn cedar_rows(forward: &law1::PropellerMap) -> [Vec<PropellerCellDefinition>; 2] {
    NEGATIVE_ADVANCE_RATIO_KNOTS.map(|j| {
        forward
            .definition()
            .blade_pitch_rad
            .iter()
            .map(|&beta| {
                let ct = 0.5 * (beta - (j / (0.75 * PI)).atan());
                // Original continuation reference, not an adverse-flow theorem.
                let reference = ct / 2.0 * (j + (j * j + 8.0 * ct / PI).sqrt());
                PropellerCellDefinition {
                    ct,
                    cp: 1.22 * reference + 0.005 + 0.01 * beta,
                }
            })
            .collect()
    })
}
fn cedar() -> TurbopropAircraftConfig {
    let forward = cedar_forward();
    let rows = cedar_rows(forward.propeller());
    TurbopropAircraftConfig::from_forward(forward, rows).unwrap()
}
fn boundary_state() -> TurbopropState {
    let f: serde_json::Value = serde_json::from_str(include_str!(
        "../../../tests/fixtures/cedar-law1-calm-braking-boundary.json"
    ))
    .unwrap();
    let a: Vec<_> = f["last_committed_state"]["canonical_state_bits_hex"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| f64::from_bits(u64::from_str_radix(v.as_str().unwrap(), 16).unwrap()))
        .collect();
    TurbopropState {
        rigid_body: RigidBodyState {
            position: Ecef(DVec3::new(a[0], a[1], a[2])),
            velocity: DVec3::new(a[3], a[4], a[5]),
            orientation: DQuat::from_xyzw(a[6], a[7], a[8], a[9]),
            angular_velocity: DVec3::new(a[10], a[11], a[12]),
        },
        turbine_fraction: TurbineFraction::new(a[13]).unwrap(),
        shaft_rad_s: RadiansPerSecond(a[14]),
        blade_pitch_rad: Radians(a[15]),
    }
}

#[test]
fn cedar_exact_law1_boundary_remains_rejected_and_law2_executes_same_input() {
    let state = boundary_state();
    let controls = ControlInputs::neutral().with_brakes(1.0);
    let environment = Environment::still_air();
    let dt = Seconds(1.0 / 120.0);
    let mut old = law1::TurbopropFlightDynamics::new(cedar_forward(), state).unwrap();
    let error = old.step(dt, controls, &environment).unwrap_err();
    assert_eq!(error.stage, TurbopropStage::K2);
    assert_eq!(error.substep, 2);
    assert!(
        matches!(error.reason, law1::TurbopropFailureReason::OutsidePropellerDomain(d)
        if d.advance_ratio == AxisStatus::Below && d.blade_pitch == AxisStatus::Within)
    );
    assert_eq!(
        error
            .diagnostics
            .values()
            .advance_ratio
            .unwrap()
            .0
            .to_bits(),
        (-4.878_198_680_520_810_5e-6_f64).to_bits()
    );
    assert_eq!(state_bits(old.state()), state_bits(&state));
    let mut new = TurbopropFlightDynamics::new(cedar(), state).unwrap();
    let report = new.step(dt, controls, &environment).unwrap();
    assert!(report.substeps >= 3 && report.substeps <= MAX_TURBOPROP_SUBSTEPS);
    assert_ne!(state_bits(new.state()), state_bits(&state));
    assert!(new.state().rigid_body.is_finite());
}

#[test]
fn forward_queries_and_steps_remain_bit_exact() {
    let config = cedar();
    let map = config.propeller();
    for j in [-0.0, 0.0, 0.025, 0.25, 0.95, 1.4] {
        for beta in [0.07, 0.083, 0.24, 0.719, 0.72] {
            let q = query(j, beta);
            assert_eq!(
                map.sample(q, KilogramsPerCubicMeter(1.225), RadiansPerSecond(180.0)),
                map.forward_map()
                    .sample(q, KilogramsPerCubicMeter(1.225), RadiansPerSecond(180.0))
                    .map_err(Into::into)
            );
        }
    }
    let mut start = level(1000.0, 40.0);
    start.blade_pitch_rad = Radians(0.35);
    let mut old =
        law1::TurbopropFlightDynamics::new(config.forward_config().clone(), start).unwrap();
    let mut new = TurbopropFlightDynamics::new(config, start).unwrap();
    let controls = ControlInputs::neutral().with_throttle(0.4);
    for _ in 0..120 {
        assert_eq!(
            old.step(Seconds(1.0 / 120.0), controls, &Environment::still_air())
                .unwrap(),
            new.step(Seconds(1.0 / 120.0), controls, &Environment::still_air())
                .unwrap()
        );
        assert_eq!(state_bits(old.state()), state_bits(new.state()));
    }
}

#[test]
fn explicit_negative_rows_and_zero_are_continuous_with_static_power_margin() {
    let config = cedar();
    let map = config.propeller();
    for (r, &j) in NEGATIVE_ADVANCE_RATIO_KNOTS.iter().enumerate() {
        for (p, &beta) in map
            .forward_map()
            .definition()
            .blade_pitch_rad
            .iter()
            .enumerate()
        {
            let c = map.coefficients(query(j, beta)).unwrap();
            assert_eq!(c.ct.to_bits(), map.negative_rows()[r][p].ct.to_bits());
            assert_eq!(c.cp.to_bits(), map.negative_rows()[r][p].cp.to_bits());
        }
    }
    let pitches = &map.forward_map().definition().blade_pitch_rad;
    let mut smallest_margin = f64::INFINITY;
    for (r, &j0) in NEGATIVE_ADVANCE_RATIO_KNOTS.iter().enumerate() {
        let j1 = if r == 0 {
            NEGATIVE_ADVANCE_RATIO_KNOTS[1]
        } else {
            0.0
        };
        for p in pitches.windows(2) {
            for a in 0..=16 {
                for b in 0..=16 {
                    let j = j0 + (j1 - j0) * f64::from(a) / 16.0;
                    let beta = p[0] + (p[1] - p[0]) * f64::from(b) / 16.0;
                    let c = map.coefficients(query(j, beta)).unwrap();
                    let floor = (2.0 / PI).sqrt() * c.ct.powf(1.5);
                    smallest_margin = smallest_margin.min(c.cp - floor);
                    assert!(c.ct > 0.0 && c.cp > 0.0 && c.cp >= floor);
                }
            }
        }
    }
    close(smallest_margin, 0.006_732_719_705_404_812_5, 1e-15);
    for beta in [0.07, 0.24, 0.719, 0.72] {
        let zero = map
            .sample(
                query(0.0, beta),
                KilogramsPerCubicMeter(1.0),
                RadiansPerSecond(180.0),
            )
            .unwrap();
        for j in [-1e-12, -f64::from_bits(1), -0.0, f64::from_bits(1), 1e-12] {
            let adjacent = map
                .sample(
                    query(j, beta),
                    KilogramsPerCubicMeter(1.0),
                    RadiansPerSecond(180.0),
                )
                .unwrap();
            close(adjacent.thrust.get(), zero.thrust.get(), 1e-6);
            close(
                adjacent.absorbed_power.get(),
                zero.absorbed_power.get(),
                1e-4,
            );
            close(adjacent.load_torque.get(), zero.load_torque.get(), 1e-6);
        }
    }
}

#[test]
fn static_floor_rejects_continuation_only_power_nonpositive_and_underflow() {
    let forward = cedar_forward();
    for (ct, cp) in [
        (0.1, 0.025),
        (0.1, 0.0),
        (0.1, -0.0),
        (0.0, 0.08),
        (-0.01, 0.08),
        (f64::from_bits(1), 0.08),
        (f64::NAN, 0.08),
        (0.1, f64::INFINITY),
    ] {
        let mut rows = cedar_rows(forward.propeller());
        rows[0][0] = PropellerCellDefinition { ct, cp };
        assert!(
            PropellerMap::from_forward(forward.propeller().clone(), rows).is_err(),
            "{ct} {cp}"
        );
    }
    let mut rows = cedar_rows(forward.propeller());
    rows[1].pop();
    assert!(PropellerMap::from_forward(forward.propeller().clone(), rows).is_err());
    let mut rows = cedar_rows(forward.propeller());
    rows[0][0].cp = 1.0;
    assert!(PropellerMap::from_forward(forward.propeller().clone(), rows).is_err());
    // A negative/nonpositive static endpoint was legal to law1, but cannot
    // furnish the new branch's continuous positive-thrust closure.
    let mut d = propeller_definition();
    d.cells[0].ct = 0.0;
    let old = law1::PropellerMap::from_definition(d).unwrap();
    let row = vec![PropellerCellDefinition { ct: 0.01, cp: 0.03 }; 2];
    assert!(PropellerMap::from_forward(old, [row.clone(), row]).is_err());
}

#[test]
fn signed_domain_edges_are_exact_and_not_clamped() {
    let config = cedar();
    let map = config.propeller();
    for j in [
        -0.01,
        (-0.01_f64).next_up(),
        -0.005,
        -f64::from_bits(1),
        -0.0,
        0.0,
    ] {
        assert!(map.coefficients(query(j, 0.07)).is_ok());
    }
    for j in [
        (-0.01_f64).next_down(),
        -1.0,
        f64::NAN,
        f64::INFINITY,
        f64::NEG_INFINITY,
    ] {
        assert!(map.coefficients(query(j, 0.07)).is_err());
    }
    for beta in [(0.07_f64).next_down(), (0.72_f64).next_up(), f64::NAN] {
        assert!(map.coefficients(query(-0.005, beta)).is_err());
    }
    for value in [
        0.0,
        -1.0,
        f64::from_bits(1),
        f64::NAN,
        f64::INFINITY,
        f64::MAX,
    ] {
        assert!(
            map.sample(
                query(-0.005, 0.07),
                KilogramsPerCubicMeter(value),
                RadiansPerSecond(180.0)
            )
            .is_err()
        );
        assert!(
            map.sample(
                query(-0.005, 0.07),
                KilogramsPerCubicMeter(1.0),
                RadiansPerSecond(value)
            )
            .is_err()
        );
    }
}

#[test]
fn hover_scale_ratio_bounds_include_exact_endpoints_and_reject_adjacent_outside() {
    let check = |axial, transverse| {
        propeller::flow_scale(
            Newtons(200.0 * PI),
            KilogramsPerCubicMeter(1.0),
            Meters(2.0),
            MetersPerSecond(axial),
            MetersPerSecond(transverse),
        )
        .unwrap()
    };
    let exact = check(-1.0, 1.0);
    assert_eq!(exact.hover_velocity.get().to_bits(), 10.0_f64.to_bits());
    assert_eq!(exact.adverse_ratio.to_bits(), 0.1_f64.to_bits());
    assert_eq!(exact.transverse_ratio.to_bits(), 0.1_f64.to_bits());
    assert!(exact.domain().is_supported());
    assert!(
        check((-1.0_f64).next_up(), (1.0_f64).next_down())
            .domain()
            .is_supported()
    );
    assert_eq!(
        check((-1.0_f64).next_down(), 1.0).domain().adverse_inflow,
        AxisStatus::Above
    );
    assert_eq!(
        check(-1.0, (1.0_f64).next_up()).domain().transverse_inflow,
        AxisStatus::Above
    );
    for thrust in [0.0, -1.0, f64::from_bits(1), f64::MAX, f64::NAN] {
        let density = if thrust.to_bits() == f64::MAX.to_bits() {
            f64::from_bits(1)
        } else {
            1.0
        };
        assert!(
            propeller::flow_scale(
                Newtons(thrust),
                KilogramsPerCubicMeter(density),
                Meters(2.0),
                MetersPerSecond(-1.0),
                MetersPerSecond(0.0)
            )
            .is_none()
        );
    }
}

#[test]
fn negative_flow_checks_add_to_existing_limits_and_keep_full_state_atomic() {
    let mut state = level(1000.0, 0.0);
    state.rigid_body.velocity = state.rigid_body.orientation * DVec3::new(-0.1, 1.0, 0.0);
    let mut model = TurbopropFlightDynamics::new(config(), state).unwrap();
    let e = model
        .step(
            Seconds::ZERO,
            ControlInputs::neutral(),
            &Environment::still_air(),
        )
        .unwrap_err();
    assert!(
        matches!(e.reason, TurbopropFailureReason::OutsideNearStaticDomain(d) if d.transverse_inflow == AxisStatus::Above)
    );
    assert!(e.diagnostics.values().transverse_inflow_ratio.unwrap() > 0.1);
    assert_eq!(state_bits(model.state()), state_bits(&state));

    // This fixture's smaller CT reaches the adverse ratio before J=-0.01.
    state.rigid_body.velocity = state.rigid_body.orientation * DVec3::new(-0.5, 0.0, 0.0);
    model.set_state(state).unwrap();
    let e = model
        .step(
            Seconds::ZERO,
            ControlInputs::neutral(),
            &Environment::still_air(),
        )
        .unwrap_err();
    assert!(
        matches!(e.reason, TurbopropFailureReason::OutsideNearStaticDomain(d) if d.adverse_inflow == AxisStatus::Above)
    );
    assert!(e.diagnostics.values().advance_ratio.unwrap().0 > -0.01);
    assert_eq!(state_bits(model.state()), state_bits(&state));
    // At positive flow the same transverse velocity retains law1's behavior.
    state.rigid_body.velocity = state.rigid_body.orientation * DVec3::new(0.1, 1.0, 0.0);
    model.set_state(state).unwrap();
    model
        .step(
            Seconds::ZERO,
            ControlInputs::neutral(),
            &Environment::still_air(),
        )
        .unwrap();
    // Existing tangential crossflow and tip limits still precede the new guard.
    state.rigid_body.velocity = state.rigid_body.orientation * DVec3::new(-0.1, 30.0, 0.0);
    model.set_state(state).unwrap();
    assert!(
        matches!(model.step(Seconds::ZERO, ControlInputs::neutral(), &Environment::still_air()).unwrap_err().reason,
        TurbopropFailureReason::OutsideOperatingEnvelope(d) if d.crossflow == AxisStatus::Above)
    );
    assert_eq!(state_bits(model.state()), state_bits(&state));
}

#[test]
fn a_negative_velocity_cannot_underflow_into_the_forward_zero_branch() {
    let mut state = level(1000.0, 0.0);
    state.rigid_body.orientation = DQuat::IDENTITY;
    state.rigid_body.velocity = DVec3::new(-f64::from_bits(1), 0.0, 0.0);
    let mut model = TurbopropFlightDynamics::new(config(), state).unwrap();
    let e = model
        .step(
            Seconds::ZERO,
            ControlInputs::neutral(),
            &Environment::still_air(),
        )
        .unwrap_err();
    assert_eq!(e.reason, TurbopropFailureReason::InvalidNearStaticScale);
    assert_eq!(state_bits(model.state()), state_bits(&state));
    assert!(
        propeller::flow_scale(
            Newtons(200.0 * PI),
            KilogramsPerCubicMeter(1.0),
            Meters(2.0),
            MetersPerSecond(-f64::from_bits(1)),
            MetersPerSecond(0.0)
        )
        .is_none()
    );
}

#[test]
fn adverse_branch_stage_and_later_substep_guard_failures_roll_back_every_bit() {
    // Horizontal flight axes and downward velocity: gravity carries the
    // transverse flow through the fixed limit. There is no controller or
    // artificial force, velocity clamp, lowered bound or altered gear here.
    for (downward, dt, stage, substep) in [
        (0.5, 1.0 / 120.0, TurbopropStage::Initial, 0),
        (0.42, 1.0 / 120.0, TurbopropStage::K2, 0),
        (0.40, 1.0 / 120.0, TurbopropStage::K4, 0),
        (0.32, 1.0 / 60.0, TurbopropStage::K4, 1),
    ] {
        let mut start = level(1000.0, 0.0);
        start.rigid_body.velocity = start.rigid_body.orientation * DVec3::new(-0.1, 0.0, downward);
        let mut model = TurbopropFlightDynamics::new(config(), start).unwrap();
        let e = model
            .step(
                Seconds(dt),
                ControlInputs::neutral(),
                &Environment::still_air(),
            )
            .unwrap_err();
        assert_eq!(e.stage, stage);
        assert_eq!(e.substep, substep);
        assert!(
            matches!(e.reason, TurbopropFailureReason::OutsideNearStaticDomain(d) if d.transverse_inflow == AxisStatus::Above)
        );
        assert!(e.diagnostics.values().advance_ratio.unwrap().0 < 0.0);
        assert_eq!(state_bits(model.state()), state_bits(&start));
    }
}

#[test]
fn negative_flow_preserves_both_rotation_senses_torque_energy_and_signed_work() {
    for sense in [-1, 1] {
        let mut r = propeller_definition();
        r.rotation_sense = sense;
        let cfg = config_from(
            airframe_definition(),
            power_definition(),
            r,
            governor_definition(),
            envelope_definition(),
        )
        .unwrap();
        let mut state = level(1000.0, 0.0);
        state.rigid_body.velocity = state.rigid_body.orientation * DVec3::new(-0.1, 0.0, 0.0);
        state.rigid_body.angular_velocity = DVec3::new(0.3, -0.2, 0.1);
        let b = state.rigid_body.angular_velocity;
        let w = state.shaft_rad_s.get();
        let s = f64::from(sense);
        let absolute = w + s * b.x;
        let rho = crate::Atmosphere::standard()
            .sample(state.rigid_body.position.to_geodetic().altitude)
            .density
            .get();
        let n = absolute / (2.0 * PI);
        let cp = 0.12;
        let qp = cp * rho * n.powi(3) * 32.0 / absolute;
        let qd = (30_000.0 + 220_000.0 * 0.4) / w;
        let model = TurbopropFlightDynamics::new(cfg.clone(), state).unwrap();
        let d = model
            .derivative(&state, ControlInputs::neutral(), &Environment::still_air())
            .unwrap();
        let alpha = d.rigid_body.angular_acceleration;
        let wd = d.shaft_acceleration.get();
        let inertia = cfg.airframe().mass_properties().inertia();
        let rotor = 20.0;
        let energy_dot =
            b.dot(inertia * alpha) + s * rotor * (wd * b.x + w * alpha.x) + rotor * w * wd;
        close(energy_dot, qd * w - qp * absolute, 2e-9);
        let momentum = inertia * b + DVec3::X * (s * rotor * w);
        let momentum_dot_inertial =
            inertia * alpha + DVec3::X * (s * rotor * wd) + b.cross(momentum);
        close(
            (momentum_dot_inertial + DVec3::X * (s * qp)).length(),
            0.0,
            1e-10,
        );
        let loads = cfg
            .propeller()
            .sample(
                query(-0.1 / (n * 2.0), 0.3),
                KilogramsPerCubicMeter(rho),
                RadiansPerSecond(absolute),
            )
            .unwrap();
        close(
            loads.absorbed_power.get(),
            loads.load_torque.get() * absolute,
            1e-9,
        );
        assert!(loads.thrust.get() * -0.1 < 0.0);
    }
}
use crate::{
    ControlInputs, Environment, RigidBodyState,
    definition::{AerodynamicDefinition, GearDefinition},
    subsonic::{AirframeDefinition, MachAeroDefinition, MachAeroKnotDefinition, MachAeroSchedule},
};
use flightsim_core::{
    Attitude, Ecef, Geodetic, KilogramsPerCubicMeter, Ned, Radians, RadiansPerSecond, Seconds,
};
use glam::{DQuat, DVec3};
use std::f64::consts::PI;

fn close(a: f64, b: f64, tol: f64) {
    assert!(
        (a - b).abs() <= tol,
        "{a:.17e} != {b:.17e}; error {}",
        (a - b).abs()
    );
}
fn power_definition() -> TurbineDefinition {
    TurbineDefinition {
        schema: 1,
        pressure_ratios: vec![0.1, 2.0],
        temperature_ratios: vec![0.25, 2.0],
        cells: vec![
            PowerCellDefinition {
                idle_w: 30_000.0,
                maximum_w: 250_000.0
            };
            4
        ],
        rise_seconds: 1.0,
        fall_seconds: 2.0,
        output_torque_limit_nm: 5000.0,
    }
}
fn propeller_definition() -> PropellerDefinition {
    PropellerDefinition {
        schema: 1,
        convention: PropellerConvention::IsolatedAxialPropeller,
        diameter_m: 2.0,
        rotor_axial_inertia_kg_m2: 20.0,
        rotation_sense: 1,
        advance_ratio: vec![0.0, 2.0],
        blade_pitch_rad: vec![0.1, 0.7],
        cells: vec![
            PropellerCellDefinition { ct: 0.01, cp: 0.03 },
            PropellerCellDefinition { ct: 0.01, cp: 0.3 },
            PropellerCellDefinition { ct: 0.01, cp: 0.03 },
            PropellerCellDefinition { ct: 0.01, cp: 0.3 },
        ],
    }
}
fn governor_definition() -> GovernorDefinition {
    GovernorDefinition {
        schema: 1,
        reference_rad_s: 180.0,
        gain: 0.001,
        fine_rate_rad_s: 0.05,
        coarse_rate_rad_s: 0.05,
        minimum_pitch_rad: 0.1,
        maximum_pitch_rad: 0.7,
    }
}
fn envelope_definition() -> TurbopropEnvelopeDefinition {
    TurbopropEnvelopeDefinition {
        pressure_ratio: [0.1, 2.0],
        temperature_ratio: [0.25, 2.0],
        mach: [0.0, 0.8],
        relative_shaft_rad_s: [40.0, 260.0],
        absolute_spin_rad_s: [40.0, 260.0],
        maximum_helical_tip_mach: 0.8,
        maximum_crossflow_tip_ratio: 0.1,
    }
}
fn airframe_definition() -> AirframeDefinition {
    let gear = |x, y| GearDefinition {
        contact_m: [x, y, 1.2],
        spring_n_per_m: 90_000.0,
        damping_ns_per_m: 9000.0,
        max_stroke_m: 0.3,
        bottom_stop_travel_m: 0.05,
        max_recoil_mps: 0.5,
    };
    AirframeDefinition {
        name: "Original turboprop numerical fixture".into(),
        mass_kg: 2000.0,
        inertia_kg_m2: [3000.0, 5000.0, 7000.0, 0.0],
        wing_area_m2: 20.0,
        wing_span_m: 12.0,
        mean_chord_m: 1.6,
        landing_gear: [gear(2.0, 0.0), gear(-1.0, -1.5), gear(-1.0, 1.5)],
        rolling_friction: 0.02,
        braking_friction: 0.7,
        lateral_friction: 0.8,
        friction_transition_mps: 0.3,
    }
}
fn schedule() -> MachAeroSchedule {
    let aero = AerodynamicDefinition {
        lift_zero: 0.0,
        lift_alpha: 0.0,
        lift_flaps: 0.0,
        stall_angle_rad: 0.3,
        stall_blend_rate: 20.0,
        drag_min: 0.01,
        oswald_efficiency: 0.8,
        drag_flaps: 0.0,
        side_beta: 0.0,
        side_rudder: 0.0,
        roll_beta: 0.0,
        roll_rate_p: 0.0,
        roll_rate_r: 0.0,
        roll_aileron: 0.0,
        roll_rudder: 0.0,
        pitch_zero: 0.0,
        pitch_alpha: 0.0,
        pitch_rate_q: 0.0,
        pitch_elevator: 0.0,
        pitch_flaps: 0.0,
        yaw_beta: 0.0,
        yaw_rate_p: 0.0,
        yaw_rate_r: 0.0,
        yaw_aileron: 0.0,
        yaw_rudder: 0.0,
    };
    MachAeroSchedule::from_definition(MachAeroDefinition {
        schema: 1,
        knots: vec![
            MachAeroKnotDefinition { mach: 0.0, aero },
            MachAeroKnotDefinition { mach: 0.8, aero },
        ],
    })
    .unwrap()
}
#[allow(
    clippy::needless_pass_by_value,
    reason = "fixture builder consistently consumes its independent definitions"
)]
fn config_from(
    a: AirframeDefinition,
    p: TurbineDefinition,
    r: PropellerDefinition,
    g: GovernorDefinition,
    e: TurbopropEnvelopeDefinition,
) -> Result<TurbopropAircraftConfig, TurbopropConfigError> {
    let forward = law1::TurbopropAircraftConfig::new(
        a.to_config().unwrap(),
        TurbinePowerTable::from_definition(p)?,
        law1::PropellerMap::from_definition(r)?,
        SampledGovernor::from_definition(g)?,
        schedule(),
        TurbopropEnvelope::from_definition(e)?,
    )?;
    let row = forward.propeller().definition().cells[..2].to_vec();
    TurbopropAircraftConfig::from_forward(forward, [row.clone(), row])
}
fn config() -> TurbopropAircraftConfig {
    config_from(
        airframe_definition(),
        power_definition(),
        propeller_definition(),
        governor_definition(),
        envelope_definition(),
    )
    .unwrap()
}
fn level(height: f64, speed: f64) -> TurbopropState {
    TurbopropState {
        rigid_body: RigidBodyState::from_geodetic(
            Geodetic::from_degrees(0.0, 0.0, height),
            Attitude::default(),
            Ned::new(speed, 0.0, 0.0),
        ),
        turbine_fraction: TurbineFraction::new(0.4).unwrap(),
        shaft_rad_s: RadiansPerSecond(180.0),
        blade_pitch_rad: Radians(0.3),
    }
}
fn state_bits(s: &TurbopropState) -> [u64; 16] {
    let b = s.rigid_body;
    let p = b.position.as_vec();
    let v = b.velocity;
    let q = b.orientation;
    let w = b.angular_velocity;
    [
        p.x,
        p.y,
        p.z,
        v.x,
        v.y,
        v.z,
        q.x,
        q.y,
        q.z,
        q.w,
        w.x,
        w.y,
        w.z,
        s.turbine_fraction.get(),
        s.shaft_rad_s.get(),
        s.blade_pitch_rad.get(),
    ]
    .map(f64::to_bits)
}
fn query(j: f64, pitch: f64) -> PropellerQuery {
    PropellerQuery {
        advance_ratio: AdvanceRatio(j),
        blade_pitch: Radians(pitch),
    }
}

#[test]
fn stage_and_later_substep_failures_restore_the_entire_call() {
    let start = level(1000.0, 40.0);
    let controls = ControlInputs::neutral().with_throttle(1.0);
    for (maximum, dt, expected_stage, expected_substep) in [
        (180.01, 1.0 / 120.0, TurbopropStage::K2, 0),
        (180.0215, 1.0 / 120.0, TurbopropStage::K3, 0),
        (180.03, 1.0 / 120.0, TurbopropStage::K4, 0),
        (180.06, 1.0 / 60.0, TurbopropStage::K2, 1),
    ] {
        let mut e = envelope_definition();
        e.relative_shaft_rad_s[1] = maximum;
        let mut model = TurbopropFlightDynamics::new(
            config_from(
                airframe_definition(),
                power_definition(),
                propeller_definition(),
                governor_definition(),
                e,
            )
            .unwrap(),
            start,
        )
        .unwrap();
        let error = model
            .step(Seconds(dt), controls, &Environment::still_air())
            .unwrap_err();
        assert_eq!(error.stage, expected_stage);
        assert_eq!(error.substep, expected_substep);
        assert_eq!(state_bits(model.state()), state_bits(&start));
    }
    let mut model = TurbopropFlightDynamics::new(config(), start).unwrap();
    model
        .step(Seconds(1.0 / 120.0), controls, &Environment::still_air())
        .unwrap();
    println!("endpoint shaft {:.17}", model.state().shaft_rad_s.get());
}

#[test]
fn endpoint_only_failure_is_checked_before_commit() {
    // Independently selected interval lies between this case's K4 shaft
    // 180.11406012828962 and weighted endpoint 180.11406014776125.
    let mut start = level(1000.0, 40.0);
    start.turbine_fraction = TurbineFraction::new(0.2).unwrap();
    start.blade_pitch_rad = Radians(0.1);
    let mut envelope = envelope_definition();
    envelope.relative_shaft_rad_s[1] = 180.11406013802542;
    let mut model = TurbopropFlightDynamics::new(
        config_from(
            airframe_definition(),
            power_definition(),
            propeller_definition(),
            governor_definition(),
            envelope,
        )
        .unwrap(),
        start,
    )
    .unwrap();
    let error = model
        .step(
            Seconds(1.0 / 120.0),
            ControlInputs::neutral(),
            &Environment::still_air(),
        )
        .unwrap_err();
    assert_eq!(error.stage, TurbopropStage::Endpoint);
    assert_eq!(error.substep, 0);
    assert_eq!(state_bits(model.state()), state_bits(&start));
}

#[test]
fn finite_guards_prevent_legacy_helpers_from_masking_bad_inputs() {
    let s = level(1000.0, 40.0);
    for wind in [DVec3::splat(f64::NAN), DVec3::splat(f64::MAX)] {
        let mut model = TurbopropFlightDynamics::new(config(), s).unwrap();
        let mut env = Environment::still_air();
        env.wind_ecef = wind;
        assert_eq!(
            model
                .step(Seconds::ZERO, ControlInputs::default(), &env)
                .unwrap_err()
                .reason,
            TurbopropFailureReason::InvalidInput(TurbopropInvalidInput::Wind)
        );
    }
    for mutate in [0, 1, 2, 3] {
        let mut bad = s;
        match mutate {
            0 => bad.rigid_body.velocity = DVec3::splat(f64::MAX),
            1 => bad.rigid_body.position = Ecef(DVec3::ZERO),
            2 => bad.rigid_body.orientation = DQuat::from_xyzw(0.0, 0.0, 0.0, 2.0),
            _ => bad.rigid_body.angular_velocity = DVec3::splat(f64::MAX),
        }
        assert!(TurbopropFlightDynamics::new(config(), bad).is_err());
    }
}
