// Generated by scripts/bake_climate.py; do not edit independently of the atlas.
/// Identity of the bundled monthly climate data and quantization.
pub const GLOBAL_CLIMATE_DATASET_ID: &str = "NOAA-NCEP-NCAR-R1-1991-2020-monthly-EGM2008-v1";
/// FNV-1a identity of the climate payload; replay compatibility, not security.
pub const GLOBAL_CLIMATE_FINGERPRINT: u64 = 0x33f6a12038b9f6b8;
